{
 "title": "Shelly Plug",
 "description": "Shelly plug switch data and state",
 "tags": [
  "shelly",
  "plug",
  "power"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "shelly_name",
    "label": "Shelly",
    "query": {
     "query": "label_values(shelly_uptime_seconds,name)"
    }
   },
   {
    "name": "switch",
    "label": "Switch",
    "query": {
     "query": "label_values(shelly_switch_power_watts,switch)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "How long the Plug has been powered on",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(shelly_uptime_seconds{name=\"$shelly_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "gauge",
   "description": "The mount of free RAM on the internal computer",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelly_switch_current_amperes{name=\"$shelly_name\",switch=\"$switch\"})by (name)",
     "legendFormat": "Power"
    }
   ]
  },
  { "title": "switch:$switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "switch" },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(shelly_switch_output{name=\"$shelly_name\",switch=\"$switch\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instant power",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelly_switch_power_watts{name=\"$shelly_name\",switch=\"$switch\"})by (name)",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Instant Current",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelly_switch_current_amperes{name=\"$shelly_name\",switch=\"$switch\"})by (name)",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Instant Volage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelly_switch_voltage_volts{name=\"$shelly_name\",switch=\"$switch\"})by (name)",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Internal temperature of the plug (including heat generated by the CPU. This does not reflect ambient temperature)",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(shelly_switch_temperature_celsius{name=\"$shelly_name\",switch=\"$switch\"})by (name)",
     "legendFormat": "Power"
    }
   ]
  },
  {
   "title": "Energy consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(shelly_switch_power_total{name=\"$shelly_name\",switch=\"$switch\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instant power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(shelly_switch_power_watts{name=\"$shelly_name\",switch=\"$switch\"})by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Energy consumption",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "avg(irate(shelly_switch_power_total{}[5m]))by (name) * 60 * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}