on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.4
    - name: execute script
      run: |
        python ./tools/json-to-md.py ./on-edit.json
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update the .md file for ${{ github.event.pull_request.title }}"
        git push
